<?xml version="1.0" encoding="utf-8"?><Database Name="ChatServerUsingSignalR" Class="ChatDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=RAJEEV2015;Initial Catalog=ChatServerUsingSignalR;Persist Security Info=True;User ID=sa" SettingsObjectName="ExampleSignalR.DAL.Properties.Settings" SettingsPropertyName="ChatServerUsingSignalRConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GetUser" Method="GetUser">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(400)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(1000)" />
    <ElementType Name="GetUserResult">
      <Column Name="UserName" Type="System.String" DbType="NVarChar(801) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AddUser" Method="AddUser">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="NVarChar(400)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="NVarChar(400)" />
    <Return Type="System.Int32" />
  </Function>
</Database>